/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EventsRouteRouteImport } from './routes/events/route'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as EventsMyEventsRouteImport } from './routes/events/my-events'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as AccountSignupRouteImport } from './routes/account/signup'
import { Route as EventsEventIdEditRouteImport } from './routes/events/$eventId.edit'

const EventsRouteRoute = EventsRouteRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRouteRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const EventsMyEventsRoute = EventsMyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => EventsRouteRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EventsRouteRoute,
} as any)
const AccountSignupRoute = AccountSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AccountRouteRoute,
} as any)
const EventsEventIdEditRoute = EventsEventIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => EventsEventIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/events': typeof EventsRouteRouteWithChildren
  '/account/signup': typeof AccountSignupRoute
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/events/my-events': typeof EventsMyEventsRoute
  '/account/': typeof AccountIndexRoute
  '/events/': typeof EventsIndexRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account/signup': typeof AccountSignupRoute
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/events/my-events': typeof EventsMyEventsRoute
  '/account': typeof AccountIndexRoute
  '/events': typeof EventsIndexRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/events': typeof EventsRouteRouteWithChildren
  '/account/signup': typeof AccountSignupRoute
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/events/my-events': typeof EventsMyEventsRoute
  '/account/': typeof AccountIndexRoute
  '/events/': typeof EventsIndexRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/events'
    | '/account/signup'
    | '/events/$eventId'
    | '/events/my-events'
    | '/account/'
    | '/events/'
    | '/events/$eventId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account/signup'
    | '/events/$eventId'
    | '/events/my-events'
    | '/account'
    | '/events'
    | '/events/$eventId/edit'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/events'
    | '/account/signup'
    | '/events/$eventId'
    | '/events/my-events'
    | '/account/'
    | '/events/'
    | '/events/$eventId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  EventsRouteRoute: typeof EventsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRouteRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/events/my-events': {
      id: '/events/my-events'
      path: '/my-events'
      fullPath: '/events/my-events'
      preLoaderRoute: typeof EventsMyEventsRouteImport
      parentRoute: typeof EventsRouteRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof EventsRouteRoute
    }
    '/account/signup': {
      id: '/account/signup'
      path: '/signup'
      fullPath: '/account/signup'
      preLoaderRoute: typeof AccountSignupRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/events/$eventId/edit': {
      id: '/events/$eventId/edit'
      path: '/edit'
      fullPath: '/events/$eventId/edit'
      preLoaderRoute: typeof EventsEventIdEditRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
  }
}

interface AccountRouteRouteChildren {
  AccountSignupRoute: typeof AccountSignupRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountSignupRoute: AccountSignupRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface EventsEventIdRouteChildren {
  EventsEventIdEditRoute: typeof EventsEventIdEditRoute
}

const EventsEventIdRouteChildren: EventsEventIdRouteChildren = {
  EventsEventIdEditRoute: EventsEventIdEditRoute,
}

const EventsEventIdRouteWithChildren = EventsEventIdRoute._addFileChildren(
  EventsEventIdRouteChildren,
)

interface EventsRouteRouteChildren {
  EventsEventIdRoute: typeof EventsEventIdRouteWithChildren
  EventsMyEventsRoute: typeof EventsMyEventsRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteRouteChildren: EventsRouteRouteChildren = {
  EventsEventIdRoute: EventsEventIdRouteWithChildren,
  EventsMyEventsRoute: EventsMyEventsRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteRouteWithChildren = EventsRouteRoute._addFileChildren(
  EventsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  EventsRouteRoute: EventsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
